namespace: project
name: wordpress

image: 
  repository: caymankey/wordpress
  tag: ""

nfs_path_sa: /mnt/IT-Academy/nfs-data/sa2-23-23/abartoshevich/project
nfs_server_sa: 192.168.37.105

host: wp.k8s-1.sa
port: 80

service:
  name: wordpress-front
  type: ClusterIP

pvc:
  storage: 2Gi
  type: nfs 

pv:
  storage: 8Gi
  type: nfs 


env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.203.3
  - name: WORDPRESS_DB_NAME
    value: bitnami_wordpress
  - name: WORDPRESS_DB_USER
    value: admin
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
    #  - name: WP_DEBUG_LOG
    #    value: wordpress

