namespace: project
name: wordpress

image: 
  repository: caymankey/wordpress
  tag: "latest"

nfs_path_sa: /mnt/IT-Academy/nfs-data/sa2-23-23/abartoshevich/project
nfs_server_sa: 192.168.37.105

host: wp.k8s-1.sa
port: 80

service:
  name: wordpress-front
  type: ClusterIP

pvc:
  storage: 2Gi
  type: nfs 

pv:
  storage: 8Gi
  type: nfs 

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.2 
  - name: WORDPRESS_DB_NAME
    value: wordpress_db
  - name: WORDPRESS_DB_USER
    value: wordpress_user
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress_pass
