image:
  repository: "caymankey/wordpress"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wp.k8s-1.sa

persistentVolumeClaim:
  storageSize: 10Gi

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.2 
  - name: WORDPRESS_DB_NAME
    value: wordpress_db
  - name: WORDPRESS_DB_USER
    value: wordpress_user
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress_pass
